### ISSUE TITLE
[Build Error] Compilation fails on Ubuntu 24.04 / Mint 22 (Qt < 6.7 and C++23 std::println missing)

### ISSUE THREAD

**Issue by darlopvil** [RPG-Maker-Translation-Tools/rpgmtranslate-qt#9]
**Describe the bug**
First of all, no rush on this! I'm just reporting it so you are aware of the compatibility status on current stable LTS distros.The project fails to compile on **Linux Mint 22 (Ubuntu 24.04 Noble)**. The main issues are the use of QDirListing (introduced in Qt 6.7, while this base uses 6.4/6.6) and some C++23 standard library features like `std::println` and `std::format` which are not yet fully available in the default `libstdc++` of GCC 13.

I decided to compile from source because the pre-built Linux binary provided in the latest release fails to run on Linux Mint 22 / Ubuntu 24.04. It specifically asks for `libavfilter.so.11`, which belongs to FFmpeg 7, while current stable long-term support distributions are still on FFmpeg 6 (`libavfilter.so.10`). Since I couldn't run the binary, compiling seemed like the only way to get the app working on a stable system, but I hit the Qt/C++23 version wall.

**To Reproduce**
1- System: Linux Mint 22 / Ubuntu 24.04.
2- Compiler: GCC 13.3.0.
3- Run ./configure -DENABLE_LIBGIT2=OFF.
4- Run cmake --build build -j$(nproc).
5- Compilation fails around 22-25%.

**Expected behavior**
Ideally, the project should compile on current stable LTS releases, perhaps using QDirIterator as a fallback for older Qt versions and `std::cout` or a custom macro for `std::println`.

**Screenshots**
```
[ 22%] Building CXX object CMakeFiles/rpgmtranslate.dir/rpgmtranslate_autogen/mocs_compilation.cpp.o
error: QDirListing: No such file or directory
error: ‘format’ has not been declared in ‘std’
error: ‘println’ has not been declared in ‘std’
error: ‘class QByteArray’ has no member named ‘slice’
```

**Desktop:**
- OS: Linux Mint 22 "Zena" (Base: Ubuntu 24.04 Noble)
- Compiler: GCC 13.3.0
- Qt Version: 6.4.2 / 6.6.x (LTS standard)
- FFmpeg Version: 6.1.1
- CPU: AMD FX-8320 (Piledriver)

**Additional context**
Key errors from the log:

- `fatal error: QDirListing: No such file or directory`
- `error: ‘format’/‘println’ has not been declared in ‘std’`
- `error: ‘class QByteArray’ has no member named ‘slice’ `(likely `sliced()` was intended for older Qt versions).

Also, a small note: the Linux binary in Releases requires `libavfilter.so.11` (FFmpeg 7), but Ubuntu 24.04 still ships with FFmpeg 6 (`libavfilter.so.10`).

**Comment by savannstm** [comment]
Ubuntu LTS (and derivatives) are not supported, read [development docs](https://rpg-maker-translation-tools.github.io/rpgmtranslate-qt/development/). It clearly states the application requires C++23 support, Qt 6.8 and FFmpeg 7. You have to patch the code yourself and build. I already have a bunch of compatibility for Qt 6.8 (6.9+ bring a lot of QoL) and I'm not going to fuck around to bring more compatibility for Qt 6.6 (the same can be said about C++23). Ubuntu and its packaging system are fundamentally flawed because of snaps, packages are old and even Debian (which is as stable as Ubuntu LTS) has newer packages. You have to either update your repositories so they provide Qt 6.8.2 or higher or patch the code (or get newer packages by other means).
To avoid bringing FFmpeg you can disable ENABLE_ASSET_PLAYBACK feature (./configure ENABLE_ASSET_PLAYBACK=OFF).
Your only option if you want to avoid setting up newer packages or patching the code is to compile static binary on Alpine Linux (using Docker). This will require building Qt6 fully statically (which will remove the support for dynamic styling), and statically linking to musl libc.
There's no rational explanation to use Linux Mint when there's user-friendly systems based not on Ubuntu - Nobara (this one I don't like), CachyOS (this one I use myself) and Bazzite (this one has funny name).
Alternatively, switch to [LMDE](https://en.wikipedia.org/wiki/Linux_Mint#LMDE).

**Comment by darlopvil** [comment]
Thank you for the clarification. I understand the technical requirements now, although I didn't expect such an aggressive stance regarding my choice of OS. I was simply trying to use the app on a stable LTS system (Mint 22/Ubuntu 24.04), which is quite common for many users.

I will look into the options you mentioned, like disabling the asset playback or trying the Docker/Alpine route. Thanks for the guidance on the build flags.

**Comment by savannstm** [comment]
> I was simply trying to use the app on a stable LTS system (Mint 22/Ubuntu 24.04), which is quite common for many users.

LTS releases are not for many users, just like LTSC releases on Windows. Application's baseline is Debian 13 Trixie which is both stable and good. So, unfortunately for you, out-of-the-box usage is not possible on Ubuntu LTS and co.

**Comment by savannstm** [comment]
@darlopvil I dropped an AppImage of the application into the latest release - it's essentially a self-contained application with all the libraries bundled in. You can try that and check if it works on your system.

**Comment by darlopvil** [comment]
Just for the record: the AppImage doesn't work on Linux Mint 22 / Ubuntu 24.04 either. It targets `GLIBC_2.43` because it was bundled on a rolling-release system instead of being built against an older LTS baseline. Since Mint 22 ships with `GLIBC 2.39`, the binary crashes on launch with multiple `version GLIBC_2.43 not found` errors.

Per the official AppImage docs, binaries should be compiled on a system _not newer_ than the oldest target system. Bundling on a rolling release with a newer glibc effectively breaks forward compatibility — which defeats the core purpose of the format.

Thanks anyway for the effort.

**Comment by savannstm** [comment]
@darlopvil I completely don't know how AppImage format works and I don't want to know that. I recently came back to my projects, and along with Claude find out a solution to build working AppImage on an Ubuntu machine, I've already implemented it in a dockerfile and tested on my Arch Linux host machine whether it works - and it does. There's a couple of issues that persist such as no Wayland support, and, to my regret, looks like it doesn't pick up dynamic plugins from the host machine (of course, it operates in its own AppImage'd filesystem...).

So I'll work a bit on the new update as well as eliminating issues with the AppImage and will commit this in a new release, hopefully with working AppImage. Cheers.
